### ISSUE TITLE
Edges in dataset

### ISSUE THREAD

**Issue by AlexDenis** [rishizek/tensorflow-deeplab-v3#17]
Hi! First of all I'd like to thank you for this implementation and great comments and explanation. However, I faced the second problem mentioned [here](https://github.com/rishizek/tensorflow-deeplab-v3/issues/7) 
Your implementation works great on the VOC dataset, so I decided to dig deeper into the differences between VOC dataset and dataset of mine. I discovered that VOC dataset comprises borders between classes drawn with 255 color, which gets ignored later. In my dataset I only have class labels for each pixel (I have 2 classes in general) and no other line highlighting the border between classes. 
Could it be possible that the problem lies somewhere here? Also,does it matter what the exact labels for my classes are (e.g. can I use 0 and 200 or I must use consecutive labels like 0 and 1)? Looking forward to your response and thanks one more time for your work!

**Comment by rishizek** [comment]
Hi @AlexDenis , thanks for your interest in the repo.
Regarding the first question, the class 255 is ignore label, which is not used both at the training and evaluation stages. You could only use when you have ambiguities. I think the model should work without them, because COCO dataset  and others are not using the ignore label around edges.
Regarding the second question, you should use label 0 and 1 when the number of classes is 2 for example.

**Comment by AlexDenis** [comment]
Thanks a lot @rishizek ! Luckily, I changed my labels to 0 and 1 the very same day I posted this issue and it seems that it resolved my problem :) Thank you one more time!
