### ISSUE TITLE
Training own data

### ISSUE THREAD

**Issue by Finalrykku** [rishizek/tensorflow-deeplab-v3#3]
Hey, 
first of all: Great work! Keep going!

What's the point with the SegmentationClassAug? Why do we need pictures with these black color codes? Why can't we also use the SegmentationClass? 
I want to train my own data, two different types of bottles. I've made pictures with two different grey colors, but tf doesn't want to learn anything but the black background. Did I forget some basic knowledge?

Thank you!

**Comment by rishizek** [comment]
Hi @Finalrykku , Thanks for your interest in the repo.

OK. Let me explain the difference between the files in SegmentationClassAug and SegmentationClass.
1. The pictures in SegmentationClassAug look like black color codes, but they are actually not. Ordinary png file has the dimension of [Height, Width, Depth] and its depth is typically 3, i.e. RGB, or 4, i.e. RGBA. But the dimension of png files in  SegmentationClassAug has Depth = 1 and the depth dimension is used for segmentation class id.  
2. You cannot use pictures  in SegmentationClass directly because the file are ordinary png format for visualization purpose, i.e. [Height, Width, 3]. You have to convert to the same format as in SegmentationClassAug, i.e. [Height, Width, 1], meaning use depth for class id.
3. The map between class id and RGB is given [here](https://github.com/rishizek/tensorflow-deeplab-v3/blob/master/utils/preprocessing.py#L11)
4. For more detailed explanation, please refer to [Using Your Dataset section of DrSleep's repo](https://github.com/DrSleep/tensorflow-deeplab-resnet#using-your-dataset).

I hope this will help you building your model. Good luck!

**Comment by Finalrykku** [comment]
Ahh, thank you a lot! Now everything makes sense!

**Comment by JadBatmobile** [comment]
so the white outlines you see in the photos of the augmented dataset, are regions of the image that are not considered when training?
